apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/version: master-2020-09-04-v0.1.1-131-ga4c5a9c
  name: observatorium-api
  namespace: observatorium
stringData:
  tenants.yaml: |-
    "tenants":
    - "id": "FB870BF3-9F3A-44FF-9BF7-D7A047A52F43"
      "name": "telemeter"
      "oidc":
        "clientID": "telemeter"
        "clientSecret": "ov7zikeipai4neih7Chahcae"
        "issuerURL": "http://127.0.0.1:5556/dex"
        "redirectURL": "http://localhost:8080/oidc/telemeter/callback"
        "usernameClaim": "email"
